version: '3.9'


services:

  frontend:
    build:
      context: ./Frontend/frontend_app
      dockerfile: Dockerfile

    ports:
      - '3001:3001'

    volumes:
      - ./frontend:/app/frontend

    depends_on:
      - backend

  backend:
    build:
      context: ./Backend/Backend_app
      dockerfile: Dockerfile

    ports:
      - '8000:8000'

    volumes:
      - ./backend:/app/backend
